[package]
name = "distributed-random-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
distributed-random = { git = "https://github.com/andronix1/distributed-random-rs" }
libc = "0.2.149"
